### ISSUE TITLE
Found this on google, is that ok?

### ISSUE THREAD

**Issue by Obsiye** [ministryofjustice/cloud-platform-how-out-of-date-are-we#131]
Hi, I was googling to make sure our teams service wasn't on google and came across this reports site. Is that ok? Sorry if i'm stepping out of bounds just thought i'd check with you.

I was googling:

1. advanced google search "site:.service.justice.gov.uk/
2. went down a few pages
3. then got to the CP reports page

https://reports.cloud-platform.service.justice.gov.uk/repositories 

Also, side note, there are a number of hello_world apps in CloudPlatform, maybe some of those can be purged.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/25043924/168069011-826cf3b1-7cb6-46e0-bf8d-61a0e9dd127b.png">

**Comment by AntonyBishop** [comment]
Hi @Obsiye.

Thanks for your feedback. I'll include this in an upcoming money saving sprint. Turning off long-lived helloworld apps will save a some money.

On the public reports, we work completely in the open (all our repos are public) and have no issues with this information being available.

Many thanks
